openapi: 3.0.1
info:
  title: drgsubApi
  description: API Definition of drgsubApi
  version: 1.0.0
servers:
- url: http://localhost:8290/drgsubapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
